name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.SERVER_SSH_KEY }} > key.pem
      - run: rsync README.md ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/ -e "ssh -i .ssh/key.pem" -avzr
