name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      
      - run: ssh -o "StrictHostKeyChecking=no" ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} -i ~/.ssh/id_rsa ls -al
      
      - run: rsync --version
      - run: rsync README.md ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:~/ -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" -avzr
